name: x86-Darwin

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          # A workaround borrowed from here:
          #   https://github.com/actions/virtual-environments/issues/1811
          brew uninstall openssl
          brew uninstall python@2.7.17
          brew untap local/openssl
          brew untap local/python2
          # End of workaround
          brew update
          brew upgrade
          brew install llvm@11
          pip3 install lit
      - name: Build HelloWorld
        run: |
          cd HelloWorld
          mkdir build && cd build
          cmake -DCT_LLVM_INSTALL_DIR="/usr/local/opt/llvm/" ../
          make -j2
      - name: Build clang-tutor + run tests
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DCT_LLVM_INSTALL_DIR="/usr/local/opt/llvm/"  ../
          make -j2
          lit test/
