name: x86-Ubuntu

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main"
          sudo apt-get update
          sudo apt-get install -y llvm-11 llvm-11-dev clang-11 libclang-common-11-dev libclang-11-dev llvm-11-tools
          sudo pip install lit
      - name: Build HelloWorld
        run: |
          cd HelloWorld
          mkdir build && cd build
          cmake -DCT_LLVM_INSTALL_DIR=/usr/lib/llvm-11/ ../
          make -j2
          /usr/lib/llvm-11/bin/clang -cc1 -load ./libHelloWorld.so -plugin hello-world $GITHUB_WORKSPACE/test/HelloWorld-basic.cpp
      - name: Build clang-tutor + run tests
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DCT_LLVM_INSTALL_DIR=/usr/lib/llvm-11/ ../
          make -j2
          lit test/
